name: user
members:
- name: id
  type: uint64
- name: name
  type: string
- name: sex
  type: string
- name: age
  type: int
- name: skill_id
  type: uint64
- name: skill_rank
  type: int
- name: group_id
  type: uint64
- name: world_id
  type: uint64
- name: field_id
  type: uint64
- name: user_fields
  has_many: true
  extend: true
  relation:
    to: user_field
    internal: id
    external: user_id
- name: skill
  extend: true
  relation:
    to: skill
    internal: skill_id
    external: id
  render:
    inline: true
- name: group
  extend: true
  relation:
    to: group
    custom: true
  render:
    json: group
- name: world
  extend: true
  relation:
    to: world
    internal: world_id
    external: id
  render: false
index:
  primary_key: id
  unique_keys:
  - - name
  - - skill_id
    - skill_rank
  keys:
  - - group_id
  - - world_id
    - field_id
